version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders_raw
      - name: order_items_raw
      - name: events_stream
      - name: products_raw
      - name: inventory_raw
      - name: returns_raw
      - name: ad_spend_raw
